export const SET_SUGGESTED_SEATS = "SET_SUGGESTED_SEATS";
export const SET_SELECTED_CINEMA = "SET_SELECTED_CINEMA";
export const SET_SELECTED_DATE = "SET_SELECTED_DATE";
export const SET_SELECTED_TIME = "SET_SELECTED_TIME";
export const TOGGLE_LOGIN_POPUP = "TOGGLE_LOGIN_POPUP";
export const SHOW_INVITATION_FORM = "SHOW_INVITATION_FORM";
export const SET_INVITATION = "SET_INVITATION";
export const SET_QR_CODE = "SET_QR_CODE";
export const RESET_CHECKOUT = "RESET_CHECKOUT";

export const FIND_SHOWTIME = "FIND_SHOWTIME";
export const FIND_CINEMA_BOOKING = " FIND_CINEMA_BOOKING";
export const SET_LIST_CINEMA_FOLLOW_MOVIE_ID =
  "SET_LIST_CINEMA_FOLLOW_MOVIE_ID";
export const SET_LIST_RESERVATIONS = "SET_LIST_RESERVATIONS";
export const SET_SELECTED_SEATS = "SET_SELECTED_SEATS";
export const SET_DISCOUNT = "SET_DISCOUNT";
export const SET_PROMOTION = "SET_PROMOTION";
export const CURRENT_RESERVATION = "CURRENT_RESERVATION";
