export const CREATE_PROMOTION = "CREATE_PRMOTION";
export const GET_ALL_PROMOTION = "GET_ALL_PROMOTION";
export const DELETE_PROMOTION = "DELETE_PROMOTION";
export const SELECT_PROMOTION = "SELECT_PROMOTION";
