export const SET_PENDING_RESERVATION = "SET_PENDING_RESERVATION";
export const SET_PAID_RESERVATION = "SET_PAID_RESERVATION";
export const SET_CHECKIN_RESERVATION = "SET_CHECKIN_RESERVATION";
export const SET_UNCHECKIN_RESERVATION = "SET_UNCHECKIN_RESERVATION";
export const GET_MY_RESERVATIONS = "GET_MY_RESERVATIONS";
